[phases.setup]
nixPkgs = ["go", "templ"]

[phases.install]
cmds = ["go install github.com/a-h/templ/cmd/templ@latest"]

[phases.build]
cmds = ["templ generate", "go build -o out ./main.go"]

[start]
cmd = "./out"
