[phases.setup]
nixPkgs = ["go", "templ", "nodejs_23"]

[phases.install]
cmds = [
    "go install github.com/a-h/templ/cmd/templ@latest",
    "npm i -g npx",
    "npx tailwindcss -i ./public/input.css -o ./public/output.css"
]

[phases.build]
cmds = ["templ generate", "go build -o out ./main.go"]

[start]
cmd = "./out"
